version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/home/postgres/data
    env_file:
      - .env

  web:
      container_name: webstore
      build: 
        context: .
        dockerfile: Dockerfile
      command: bash -c '
               python /code/manage.py migrate --noinput &&
               python /code/manage.py runserver 0.0.0.0:8000'
      volumes: 
        - .:/code/
      ports:
        - 8000:8000
      depends_on:
        - db
volumes:
  postgres_data:
        

