# Generated by Django 2.2 on 2020-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFavicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='favicon', verbose_name='Фавикон')),
            ],
            options={
                'verbose_name': 'Фавикон сайта',
                'verbose_name_plural': 'Фавиконы сайта',
            },
        ),
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Логотип сайта',
                'verbose_name_plural': 'Логотипы сайта',
            },
        ),
        migrations.CreateModel(
            name='TemplateFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='Название шаблона')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание шаблона')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст шаблона')),
            ],
            options={
                'verbose_name': 'Файл шаблона',
                'verbose_name_plural': 'Файлы шаблона',
            },
        ),
    ]
