# Generated by Django 2.2 on 2020-11-21 15:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_active_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=tinymce.models.HTMLField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='seo_description',
            field=models.CharField(default=1, max_length=255, verbose_name='SEO Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='seo_title',
            field=models.CharField(default=1, max_length=255, verbose_name='SEO Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
    ]
