# Generated by Django 2.2 on 2021-01-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201121_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='articel',
            field=models.IntegerField(blank=True, default=2075829, verbose_name='Артикул'),
        ),
    ]
