# Generated by Django 2.2 on 2021-01-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210105_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='articel',
            field=models.IntegerField(blank=True, default=2536852, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Название'),
        ),
    ]
