# Generated by Django 2.2 on 2021-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210618_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='articel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='articel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул'),
        ),
    ]
