# Generated by Django 2.2 on 2021-01-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210106_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='articel',
            field=models.IntegerField(blank=True, default=6191107, verbose_name='Артикул'),
        ),
    ]
