# Generated by Django 2.2 on 2021-07-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210618_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_articel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryArticel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articel_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemArticel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articel_item', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='articel',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Артикул категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='articel',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Артикул товара'),
        ),
    ]
