# Generated by Django 2.2 on 2021-01-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210106_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='articel',
            field=models.IntegerField(blank=True, default=2554020, verbose_name='Артикул'),
        ),
    ]
