# Generated by Django 2.2 on 2022-03-11 11:36

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210711_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articel_children', to='store.ArticelCategory', verbose_name='Артикул категорий')),
            ],
            options={
                'verbose_name': 'Артикул',
                'verbose_name_plural': 'Артикулы',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticelItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ArticelCategory', verbose_name='Артикул')),
            ],
            options={
                'verbose_name': 'Артикул',
                'verbose_name_plural': 'Артикулы',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Articel',
        ),
        migrations.DeleteModel(
            name='CategoryArticel',
        ),
        migrations.DeleteModel(
            name='ItemArticel',
        ),
        migrations.AddField(
            model_name='item',
            name='full_articel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='category',
            name='articel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ArticelCategory', verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='item',
            name='articel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ArticelItem', verbose_name='Артикул'),
        ),
    ]
