# Generated by Django 2.2 on 2021-01-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210106_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='articel',
            field=models.IntegerField(blank=True, verbose_name='Артикул'),
        ),
    ]
