# Generated by Django 5.0.1 on 2024-01-20 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220311_1136'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='articel',
            field=models.CharField(default='000', max_length=3, verbose_name='Название'),
        ),
        migrations.RemoveField(
            model_name='articelitem',
            name='category',
        ),
        migrations.AlterField(
            model_name='item',
            name='articel',
            field=models.CharField(blank=True, default='000', max_length=3, null=True, verbose_name='Артикул товара'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='full_articel',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quanity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ArticelCategory',
        ),
        migrations.DeleteModel(
            name='ArticelItem',
        ),
    ]
