# Generated by Django 5.0.1 on 2024-02-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_category_articel_remove_articelitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_show_on_index',
            field=models.BooleanField(default='False', null='False', verbose_name='Показывать на главной странице'),
            preserve_default='False',
        ),
    ]
