# Generated by Django 5.0.1 on 2024-02-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_item_is_show_on_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_show_on_index',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
