# Generated by Django 5.0.1 on 2024-02-26 08:07

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_category_is_show_on_index'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('publishes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='active_on',
            field=models.BooleanField(default='False', null='False', verbose_name='Активная'),
            preserve_default='False',
        ),
    ]
