# Generated by Django 5.0.1 on 2024-02-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_item_managers_category_active_on'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
    ]
